version: "3.0"
services:
  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    ports:
      - "5404:5432"
    environment:
      POSTGRES_DB: grondexploitatie
      POSTGRES_USER: grondexploitatie
      POSTGRES_PASSWORD: insecure

  importer:
    build:
      context: .
    links:
      - database
    environment:
      DATABASE_NAME: grondexploitatie
      DATABASE_USER: grondexploitatie
      DATABASE_PASSWORD: insecure
      DATABASE_HOST_OVERRIDE: database
    volumes:
            - ./backups:/tmp/backups
    command: >
      bash -c "set -x && set -e && echo database:5432:grondexploitatie:grondexploitatie:insecure > ~/.pgpass &&\
               chmod 600 ~/.pgpass && \
               ls /app/src/ && \\
               /app/src/docker-wait.sh && \
               echo
               cat data/GREX_grenzen_2016.utf8.sql | psql -h localhost -p 5404  -U grondexploitatie grondexploitatie
