version: "3.0"
services:
  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    ports:
      - "5404:5432"
    environment:
      POSTGRES_DB: grondexploitatie
      POSTGRES_USER: grondexploitatie
      POSTGRES_PASSWORD: insecure

  web:
    build: src/
    ports:
      - "8000:8000"
    links:
      - database
    environment:
      - UWSGI_HTTP=0.0.0.0:8000
      - UWSGI_MODULE=grondexploitatie.wsgi
      - UWSGI_CALLABLE=application
      - UWSGI_MASTER=1
      - UWSGI_STATIC_MAP=/static=/static
      - UWSGI_STATIC_SAFE=static/
      - UWSGI_STATIC_EXPIRES=/* 3600
      - UWSGI_OFFLOAD_THREADS=3
      - UWSGI_HARAKIRI=15
      - UWSGI_DIE_ON_TERM=1
      - DATAPUNT_API_URL=${DATAPUNT_API_URL:-https://api.data.amsterdam.nl/}
      - SECRET_KEY=insecure
      - DATABASE_NAME=grondexploitatie
      - DATABASE_USER=grondexploitatie
      - DATABASE_PASSWORD=insecure
