version: "3.0"
services:
  database:
    image: amsterdam/postgres
    ports:
      - "5404:5432"
    environment:
      POSTGRES_DB: grondexploitatie
      POSTGRES_USER: grondexploitatie
      POSTGRES_PASSWORD: insecure
    volumes:
      - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"

  web:
    build: src/
    ports:
      - "8000:8000"
    links:
      - database
    environment:
      UWSGI_HTTP: ":8000"
      UWSGI_MODULE: "grondexploitatie.wsgi"
      UWSGI_CALLABLE: "application"
      UWSGI_MASTER: 1
      UWSGI_STATIC_MAP: "/grondexploitatie/static=/static"
      DATAPUNT_API_URL: ${DATAPUNT_API_URL:-https://api.data.amsterdam.nl/}
      SECRET_KEY: insecure
      DATABASE_NAME: grondexploitatie
      DATABASE_USER: grondexploitatie
      DATABASE_PASSWORD: insecure
