swagger: "2.0"
info:
    title: "Grondexploitatie API"
    description: "Beschrijving grondexploitatie API"
    version: ""
host: {{ acc_prod_prefix }}api.data.amsterdam.nl
basePath: /grondexploitatie
schemes:
  - https
produces:
  - application/json
securityDefinitions:
  OAuth2:
    type: oauth2
    description: 'Authorization through datapunt Authorization service. Scopes start with GREX for this API'
    authorizationUrl: 'https://{{ acc_prod_prefix }}api.data.amsterdam.nl/oauth2/authorize'
    flow: implicit
    scopes:
      GREX/R: Read grondexploitatie
paths:
  /projects/:
    get:
      summary: List alle projecten
      description: Geef lijst van alle projecten waarvoor er baten zijn vanaf het 'start_jaar' Default is 'start_jaar' het huidige jaar
      security:
        - OAuth2:
            - GREX/R
      parameters:
        - name: start_jaar
          in: query
          description: Het eerste jaar vanaf waar er data is
          type: string
          pattern: '^[0-9]{4}$'
          required: false
      responses:
        '200':
          description: OK

  /project/{plannr}/:
    get:
      summary: Project details
      description: Toon details voor project met baten begroot per categorie vanaf 'start_jaar' Default is 'start_jaar' het huidige jaar.
      security:
        - OAuth2:
            - GREX/R
      parameters:
        - name: plannr
          in: path
          required: true
          type: string
          pattern: '^[0-9]{5}$'
        - name: start_jaar
          in: query
          description: Het eerste jaar vanaf waar er data is.
          type: string
          pattern: '^[0-9]{4}$'
          required: false
      responses:
        '200':
          description: >-
            Project details

            _display
            plannr
            plannaam
            startdatum
            planstatus
            geometrie
            begroting
            prijspeildatum
            fase
            begroot

            Als het project bestaat maar geen begroting dan zijn de volgende velden null

            begroting
            prijspeildatum
            fase
            begroot

          schema:
            properties:
              _display:
                type: string
              plannr:
                type: integer
              plannaam:
                type: string
              startdatum:
                type: string
              planstatus:
                type: string
              geometrie:
                type: object
              prijspeildatum:
                type: string
              fase:
                type: string
              begroot:
                type: object
                additionalProperties:
                  type: array
                  items:
                    type: object
                    properties:
                      start:
                        type: string
                      end:
                        type: string
                      begroot:
                        type: integer

  /stadsdeel/{stadsdeel_code}/:
    get:
      summary: Stadsdeel details
      description: Toon details voor stadsdeel met baten begroot per categorie vanaf 'start_jaar' Default is 'start_jaar' het huidige jaar.
      security:
        - OAuth2:
            - GREX/R
      parameters:
        - name: stadsdeel_code
          in: path
          required: true
          type: string
          pattern: '^[A-Z]$'
        - name: start_jaar
          in: query
          description: Het eerste jaar vanaf waar er data is.
          type: string
          pattern: '^[0-9]{4}$'
          required: false
      responses:
        '200':
          description: >-
            Stadsdeel details

            stadsdeel_code
            stadsdeel_naam
            geometrie
            begroot
            baten

          schema:
            properties:
              stadsdeel_code:
                type: integer
              stadsdeel_naam:
                type: string
              geometrie:
                type: object
              begroot:
                type: string
              baten:
                type: object
