swagger: "2.0"
info:
    title: "Grondexploitatie API"
    description: "Beschrijving grondexploitatie API"
    version: ""
host: acc.api.data.amsterdam.nl
basePath: /grondexploitatie
schemes:
  - https
produces:
  - application/hal+json
  - application/json
securityDefinitions:
  OAuth2:
    type: oauth2
    description: 'Authorization through datapunt Authorization service. Scopes start with GREX for this API'
    authorizationUrl: 'https://acc.api.data.amsterdam.nl/oauth2/authorize'
    flow: implicit
    scopes:
      GREX/R: Read grondexploitatie
parameters:
  start_jaar:
    name: start_jaar
    in: query
    description: The year to start getting data
    type: string
    pattern: '^[1-9]{4}$'
    required: false
  use_period_groups:
    name: use_period_groups
    in: query
    description: Show results in period groups of 4 years
    type: boolean
    required: false
paths:
  /projects/:
    get:
      summary: List alle projecten
      description: Geef lijst van alle projecten waarvoor er baten zijn vanaf het 'start_jaar' Default is 'start_jaar' het huidige jaar
      security:
        - OAuth2:
            - GREX/R
      responses:
        '200':
          description: OK

  /project/{plannr}/:
    get:
      summary: Project details
      description: Toon details voor project met baten begroot per categorie vanaf 'start_jaar' Default is 'start_jaar' het huidige jaar Indien parameter 'use_period_groups' is meegegeven dan worden de bate niet alleen per categorie, maar ook per periode van vier jaar en het huidige jaar weergegeven
      security:
        - OAuth2:
            - GREX/R
      parameters:
        - name: plannr
          in: path
          required: true
          type: string
          pattern: '/^[0-9]{5}$/'
      responses:
        '200':
          description: OK