version: "3.0"
services:
  database:
    image: amsterdam/postgres11
    ports:
      - "5404:5432"
    environment:
      POSTGRES_DB: grondexploitatie
      POSTGRES_USER: grondexploitatie
      POSTGRES_PASSWORD: insecure
    volumes:
      - ./backups:/tmp/backups

  importer:
    image: build.datapunt.amsterdam.nl:5000/datapunt/grondexploitatie:${ENVIRONMENT}
#    build: ../..
    links:
      - database
    environment:
      GRONDEXPLOITATIE_OBJECTSTORE_PASSWORD: ${GRONDEXPLOITATIE_OBJECTSTORE_PASSWORD}
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_NAME: grondexploitatie
      DATABASE_USER: grondexploitatie
      DATABASE_PASSWORD: insecure
    command: >
      bash -c "./import/import.sh"
